version: 2.1

workflows:
  build_and_test:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
          context: org-global

  nightly_build:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
              - master
              - "pull/[0-9]+"
    jobs:
      - build:
          context: org-global

jobs:
  build:
    macos:
      xcode: "11.3.0"
    working_directory: ~/signing_tools
    steps:
    - checkout
    - run:
        # jq is required, but it's already set up in default CircleCI homebrew
        command: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew install bats-core golang gnu-getopt coreutils
            pip3 install -q yq
        name: macOS build machine setup
    - run:
        command: make test
        no_output_timeout: 30m


